### ISSUE TITLE
⚠ [Warning] : Resize the `/images/app-preview.gif`

### ISSUE THREAD

**Issue by xuelink** [langxapp/website#29]
This file is too big, slow load, optimize the file size.

`/images/app-preview.gif`

**Comment by neebooo** [comment]
Maybe going to .webp should help a bit (combined with resizing). Webp is supported by major browsers for a while now too

**Comment by xuelink** [comment]
Closed w/ 143753bb70cf2fb85c3d567179947637a3f2c5d8

**Comment by xuelink** [comment]
It may be have more optimized image but for now, i think its ok @neebooo @DH-555
