### ISSUE TITLE
🚀 [Feature] : Add FAQ Section

### ISSUE THREAD

**Issue by xuelink** [langxapp/website#32]
**Is your feature request related to a problem? Please describe.**
Question and answers: https://www.reddit.com/r/languagelearning/comments/1avn8xo/

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by jakebogan01** [comment]
@xuelink I'd like to take this issue on and see if I can add a fun FAQ section. Not sure if you might be able to assign me to this issue or not as an external contributor?

**Comment by xuelink** [comment]
> @xuelink I'd like to take this issue on and see if I can add a fun FAQ section. Not sure if you might be able to assign me to this issue or not as an external contributor?

First of all, thank you for your interest and intent for contributing, its really valuable for us. I assigned this issue to you and also invited you to our organization as a member.  

You can feel free to open PR about this FAQ section with your desire and intent and if do you need any help or ask any question, feel free as well 😉

**Comment by jakebogan01** [comment]
@xuelink Thanks! I'll try to get started on this sometime this week, and I'll let you know if I have any questions 👍

**Comment by jakebogan01** [comment]
@xuelink I created a PR for this [issue](https://github.com/langxapp/website/pull/49)

**Comment by xuelink** [comment]
Let me open this issue again.

@jakebogan01 Better to add here questions and answers from [here](https://www.reddit.com/r/languagelearning/comments/1avn8xo/) then you can make this section visible :) Feel free to take iniative to pick questions and answers by yourself, no problem.

If needs, later on, we can update them.

**Comment by jakebogan01** [comment]
@xuelink 

I created a word doc and based on the reddit post I made a few questions with answers. Please feel free to add/edit anything you wish. Once you approve all the questions and answers I'll go ahead and add these to the FAQ section.

[Word doc](https://docs.google.com/document/d/1kxlRIj1400EJ8pkTr2Jc_qboIU9u3lu0rrmFhfDL9vA/edit)

**Comment by xuelink** [comment]
> @xuelink
> 
> I created a word doc and based on the reddit post I made a few questions with answers. Please feel free to add/edit anything you wish. Once you approve all the questions and answers I'll go ahead and add these to the FAQ section.
> 
> [Word doc](https://docs.google.com/document/d/1kxlRIj1400EJ8pkTr2Jc_qboIU9u3lu0rrmFhfDL9vA/edit)
> 
> Side question, have you considered creating a [project](https://github.com/langxapp/website/projects?query=is%3Aopen) to more organize the app, you can have tasks for features, bugs and so on. That way you can assign each task to a person, and anyone can see where in the process a task is in real time development?

@jakebogan01 For the doc, i requested for a permission to edit. It looks awesome, thank you again.

Secondly, project feature of this repo gonna be great, i tested it several times but disable it for now, because of lack of contributors for now.

**Comment by jakebogan01** [comment]
@xuelink No worries, I accepted and you should be able to edit now.

Oh okay, yeah no worries, just wasn't sure if you aware of GitHub projects

**Comment by xuelink** [comment]
> @xuelink No worries, I accepted and you should be able to edit now.
> 
> Oh okay, yeah no worries, just wasn't sure if you aware of GitHub projects

I think its done

**Comment by xuelink** [comment]
> Oh okay, yeah no worries, just wasn't sure if you aware of GitHub projects

@jakebogan01 I just tried this tab to take a look and thats all, I think its possible to work with multiple repositories there yea ? If it is possible and if you know how to organize it and work well, then i give you an admin rights here within this organization, can you please organize this project tab for us ?

for example, im working on [these](https://discord.com/channels/1211339989967970375/1223711806116073634/1227643946499444827) issues nowadays. I can assign these issues to me that in project tabs and i can show it exactly which issue im working on it yea ?

**Comment by jakebogan01** [comment]
@xuelink I'm not sure if you can use the projects to work with multiple repos or not, I never tried that. I've only used projects fully once before and it was really fun and kept things organized. I'll see if I can get a project going under this repo and go from there, I'll let  you know what I find in this thread.

**Comment by xuelink** [comment]
> @xuelink I'm not sure if you can use the projects to work with multiple repos or not, I never tried that. I've only used projects fully once before and it was really fun and kept things organized. I'll see if I can get a project going under this repo and go from there, I'll let you know what I find in this thread.

I think we should enable it and try it all together :) It looks better than trello and less complex then jira, lets give a shot to this feature.

**Comment by xuelink** [comment]
@jakebogan01 i just created a simple project with 3 sections, "Todo", "In Process" and "Done".
Simple and easy to use. But im not sure about permissions that you can move any card between these sections. Let me know if you can do. Best

**Comment by jakebogan01** [comment]
@xuelink Looks like I am able to move the task cards without an issue. 

Also no problem, glad to help!

I think having a review column between the in progress and done would be good. That way you know which tasks someone has ready for you to review. What do you think?

**Comment by xuelink** [comment]
Thank you, im going to release new version now

**Comment by jakebogan01** [comment]
No problem, sounds good
