### ISSUE TITLE
🚀 : Add Sponsors Section to Homepage

### ISSUE THREAD

**Issue by xuelink** [langxapp/website#43]
**Is your feature request related to a problem? Please describe.**
Our platform currently lacks a dedicated section to acknowledge and highlight our sponsors. This may result in missed opportunities to showcase the support we receive from these entities and to encourage more sponsorships.

**Describe the solution you'd like**
I suggest we add a "Sponsors" section to our homepage. This section would feature logos, brief descriptions, and links to our sponsors' websites. It would not only recognize their contributions but also provide them with visibility to our users.

**Describe alternatives you've considered**
An alternative could be to mention our sponsors in blog posts or newsletters. However, having a dedicated section on our homepage ensures constant visibility and easy access for all visitors.

**Additional context**
Adding a "Sponsors" section would enhance our relationship with our sponsors and could potentially attract more sponsorships. It aligns with our goal of fostering a supportive and collaborative community.

*Contributor: @DH-555*

![Main_sponsor_20240331_211946_0000](https://github.com/langxapp/website/assets/3280475/e88a6d57-4a5c-402b-ac6c-3e793b7a3daf)

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by jakebogan01** [comment]
@xuelink I can take this one next

**Comment by xuelink** [comment]
> @xuelink I can take this one next

sure it is an example photo

<img width="1595" alt="Screenshot 2024-04-14 at 10 38 53 AM" src="https://github.com/langxapp/website/assets/3280475/48c8cb1f-cdfd-486d-94f0-696612834034">

**Comment by jakebogan01** [comment]
@xuelink Got it, I'll make it look like that. Are these the only sponsors?

Digital Ocean
Appwrite
DHSoftware

**Comment by xuelink** [comment]
@jakebogan01 To be honest, we dont have any sponsors yet but we have been trusted by companies from world's leading organizations, so we can do

**Verified by companies from world's leading organizations**
- [ ] Apple
- [ ] Google Play Store
- [ ] TikTok
- [ ] Facebook
- [ ] Google

**Supported by companies from world's growing organizations**
- [ ] Cloudflare
- [ ] Digital Ocean
- [ ] Backblaze
- [ ] Nodejs
- [ ] Appwrite

I think that's OK! What do you think about this list? @DH-555

**Comment by jakebogan01** [comment]
@xuelink no worries, I can make two sponsor rows like that no problem

**Comment by xuelink** [comment]
> @xuelink no worries, I can make two sponsor rows like that no problem
@jakebogan01 
I think if you do as a component, we can call it 2 times with different data set.
In other way, you can duplicate the component with different name, its also ok for me.
Best

**Comment by jakebogan01** [comment]
Here is my [PR](https://github.com/langxapp/website/pull/52)

**Comment by xuelink** [comment]
Thank you very much! I just merged, i understand your concerns but it looks OK for now !

**Comment by jakebogan01** [comment]
@xuelink No worries, I'll get started on the footer issue tomorrow I hope

**Comment by xuelink** [comment]
> [@xuelink](https://github.com/xuelink) No worries, I'll get started on the footer issue tomorrow I hope

@jakebogan01 every day, one part of website you are doing well !! :) 
You also add this website in your portfolio if you want, no issue :)

**Comment by jakebogan01** [comment]
@xuelink Thanks, I'm glad I can help!

**Comment by xuelink** [comment]
@jakebogan01

 ![image](https://github.com/langxapp/website/assets/3280475/2951b2e7-2f2a-4e66-b43f-20aa9b745ca7)

a new source website is now visible in our insights 😉
