### ISSUE TITLE
🚀 : Add a logo in header

### ISSUE THREAD

**Issue by xuelink** [langxapp/website#44]
**Is your feature request related to a problem? Please describe.**
No, this feature request is not related to a problem. It's a new feature to enhance the user interface of the application.
<img width="272" alt="Screenshot 2024-04-03 at 8 50 01 PM" src="https://github.com/langxapp/website/assets/3280475/099b2022-1e57-4a8c-b73e-14c3deb2108f">

**Describe the solution you'd like**
I would like to add a logo in the header of the application. This will make the application more recognizable and professional. The logo should be placed on the left side of the header and should be clearly visible.

**Describe alternatives you've considered**
An alternative could be to place the logo in the center of the header. However, placing it on the left is more conventional and expected by most users.

**Additional context**
Here's a mockup of how the header might look with the logo:

![logo2_dark_transparent(2)](https://github.com/langxapp/website/assets/3280475/4c36bb48-f11f-46ad-8f47-076bec3c16d6)

_If you want speed up process of this issue, please send 🚀 as a reaction._

**Comment by jakebogan01** [comment]
@xuelink I went ahead and created a PR. I added a dark and light SVG logo, and fixed the link that wrapped the logo.

**Comment by xuelink** [comment]
#47
